#!/bin/bash

# Author: Ayush Singh <coding.ayush@gmail.com>
# Date: October 02, 2023
# Description: This is bash script to generate the directory and file structure for this project

# Define the base directory
base_dir="src"

# Create the base directory if it doesn't exist
mkdir -p "$base_dir"

# Define the directory structure and files
directories_and_files=(
    "app/applicant/applicant.dto.ts"
    "app/applicant/applicant.service.ts"
    "app/common/common.dto.ts"
    "app/file/file.dto.ts"
    "app/file/file.service.ts"
    "app/milestone/milestone.dto.ts"
    "app/milestone/milestone.service.ts"
    "app/payroll/payroll.dto.ts"
    "app/payroll/payroll.service.ts"
    "app/profile/profile.dto.ts"
    "app/profile/profile.service.ts"
    "app/project/project.dto.ts"
    "app/project/project.service.ts"
    "app/role/role.dto.ts"
    "app/role/role.service.ts"
    "app/task/task.dto.ts"
    "app/task/task.service.ts"
    "app/team/team.dto.ts"
    "app/team/team.service.ts"
    "app/user/user.dto.ts"
    "app/user/user.service.ts"
    "app/vacancy/vacancy.dto.ts"
    "app/vacancy/vacancy.service.ts"
    "delivery/grpc/clients/task.client.ts"
    "delivery/grpc/proto/task.proto"
    "delivery/grpc/services/task.service.ts"
    "delivery/http/controllers/applicant.controller.ts"
    "delivery/http/controllers/milestone.controller.ts"
    "delivery/http/controllers/profile.controller.ts"
    "delivery/http/controllers/role.controller.ts"
    "delivery/http/controllers/team.controller.ts"
    "delivery/http/controllers/vacancy.controller.ts"
    "delivery/http/controllers/file.controller.ts"
    "delivery/http/controllers/payroll.controller.ts"
    "delivery/http/controllers/project.controller.ts"
    "delivery/http/controllers/task.controller.ts"
    "delivery/http/controllers/user.controller.ts"
    "delivery/http/middlewares/session.middleware.ts"
    "delivery/http/middlewares/validator.middleware.ts"
    "delivery/http/routes/applicant.route.ts"
    "delivery/http/routes/file.route.ts"
    "delivery/http/routes/milestone.route.ts"
    "delivery/http/routes/payroll.route.ts"
    "delivery/http/routes/profile.route.ts"
    "delivery/http/routes/project.route.ts"
    "delivery/http/routes/role.route.ts"
    "delivery/http/routes/task.route.ts"
    "delivery/http/routes/team.route.ts"
    "delivery/http/routes/user.route.ts"
    "delivery/http/routes/vacancy.route.ts"
    "delivery/websocket/handlers/chat.handler.ts"
    "delivery/websocket/handlers/handshake.handler.ts"
    "domain/applicant/applicant.ts"
    "domain/file/file.route.ts"
    "domain/milestone/milestone.ts"
    "domain/payroll/payroll.ts"
    "domain/profile/profile.ts"
    "domain/project/project.ts"
    "domain/role/role.ts"
    "domain/task/task.ts"
    "domain/team/team.ts"
    "domain/user/user.ts"
    "domain/vacancy/vacancy.ts"
    "external/github/github.client.ts"
    "external/github/github.dto.ts"
    "external/github/github.service.ts"
    "external/wakatime/wakatime.client.ts"
    "external/wakatime/wakatime.dto.ts"
    "external/wakatime/wakatime.service.ts"
    "infrastructure/data-access/mongodb/db.ts"
    "infrastructure/data-access/mongodb/models/applicant.model.ts"
    "infrastructure/data-access/mongodb/models/file.model.ts"
    "infrastructure/data-access/mongodb/models/milestone.model.ts"
    "infrastructure/data-access/mongodb/models/payroll.model.ts"
    "infrastructure/data-access/mongodb/models/profile.model.ts"
    "infrastructure/data-access/mongodb/models/project.model.ts"
    "infrastructure/data-access/mongodb/models/role.model.ts"
    "infrastructure/data-access/mongodb/models/task.model.ts"
    "infrastructure/data-access/mongodb/models/team.model.ts"
    "infrastructure/data-access/mongodb/models/user.model.ts"
    "infrastructure/data-access/mongodb/models/vacancy.model.ts"
    "infrastructure/data-access/mongodb/repositories/applicant.repository.ts"
    "infrastructure/data-access/mongodb/repositories/milestone.repository.ts"
    "infrastructure/data-access/mongodb/repositories/profile.repository.ts"
    "infrastructure/data-access/mongodb/repositories/role.repository.ts"
    "infrastructure/data-access/mongodb/repositories/team.repository.ts"
    "infrastructure/data-access/mongodb/repositories/vacancy.repository.ts"
    "infrastructure/data-access/mongodb/repositories/file.repository.ts"
    "infrastructure/data-access/mongodb/repositories/payroll.repository.ts"
    "infrastructure/data-access/mongodb/repositories/project.repository.ts"
    "infrastructure/data-access/mongodb/repositories/task.repository.ts"
    "infrastructure/data-access/mongodb/repositories/user.repository.ts"
    "infrastructure/data-access/redis/redis.client.ts"
    "infrastructure/logging/logger.ts"
    "internal/background/amqp/amqp.consumer.ts"
    "internal/background/amqp/amqp.producer.ts"
    "internal/background/cron/cron.ts"
    "internal/background/kafka/kafka.consumer.ts"
    "internal/background/kafka/kafka.producer.ts"
    "internal/scripts/maintenance.script.ts"
    "internal/scripts/migration.script.ts"
    "internal/utils/uid.util.ts"
    "meta/config/db.config.ts"
    "meta/config/fastify.config.ts"
    "meta/config/github.config.ts"
    "meta/config/redis.config.ts"
    "meta/config/wakatime.config.ts"
    "meta/constants/enums.ts"
    "meta/constants/errors.ts"
    "meta/locales/bn.json"
    "meta/locales/currencies.json"
    "meta/locales/en.json"
    "meta/locales/es.json"
    "meta/locales/fr.json"
    "meta/locales/hi.json"
    "meta/locales/locales.ts"
    "meta/locales/translations.ts"
    "meta/seeds/role.seed.json"
    "meta/seeds/user.seed.json"
    "views/index.ejs"
)

# Loop through the directories and files to create them
for item in "${directories_and_files[@]}"; do
    # Create the directory or file
    mkdir -p "$base_dir/$(dirname "$item")"
    touch "$base_dir/$item"
done

echo "Directory structure and empty files have been created."
